/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.CalculoController;
import controller.VistasController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Empleado;
import model.Pago;
import model.PagoDestino;
import model.PagoTotal;

/**
 *
 * @author Soporte
 */
public class BonosView extends javax.swing.JFrame {
    public List<Pago> pagos = new ArrayList<Pago>();
    /**
     * Creates new form BonosView
     */
    public BonosView(List<Pago> pagos, List<Empleado> empleados) {
        this.pagos = pagos;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {            
            @Override
            public void windowClosing(WindowEvent e) {
                // Cierra esta ventana
                dispose();

                // Muestra la vista de CalendarioView
                VistasController vctrl = new VistasController();
                vctrl.vistaCalendario(empleados);
                
            }
        });
    }
    CalculoController cctrl = new  CalculoController();     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCTuzoo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCZoomat = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCTamux = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCNinez = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jCDiosP = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCValle = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCTlaco = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCYumka = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jCTamatan = new javax.swing.JCheckBox();
        jBAceptar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("SELECCIONA LOS DESTINOS A LOS QUE SE LES ASIGNARA UN BONO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("TUZOOFARI");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ZOOMAT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("TAMUX");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("NIÑEZ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DIOS PADRE");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("VALLE PARAISO");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("TLACO");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("YUMKA");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("TAMATAN");

        jBAceptar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBAceptar1.setText("ACEPTAR");
        jBAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCTamatan))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCNinez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCTamux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCZoomat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCTuzoo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCDiosP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCValle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCTlaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCYumka)))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jBAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jCTuzoo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCZoomat))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCTamux))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCNinez)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jCYumka))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jCTlaco))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jCValle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jCDiosP))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCTamatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jBAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptar1ActionPerformed
           
        if(jCTuzoo.isSelected()){
            double bonTuzoo[] = new double[4];
           // Crear los campos de entrada para los bonos
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 5)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Tuzoo", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonTuzoo[0] = Double.parseDouble(BCField.getText());
                bonTuzoo[1] = Double.parseDouble(BLField.getText());
                bonTuzoo[2] = Double.parseDouble(BTCField.getText());
                bonTuzoo[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 4).collect(Collectors.toList()), bonTuzoo);
            
        }
        
        if(jCZoomat.isSelected()){
            double bonZoomat[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 5)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Zoomat", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonZoomat[0] = Double.parseDouble(BCField.getText());
                bonZoomat[1] = Double.parseDouble(BLField.getText());
                bonZoomat[2] = Double.parseDouble(BTCField.getText());
                bonZoomat[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 1).collect(Collectors.toList()), bonZoomat);
            
        }
        
        if(jCTamux.isSelected()){
            double bonTamux[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 7)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Tamux", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonTamux[0] = Double.parseDouble(BCField.getText());
                bonTamux[1] = Double.parseDouble(BLField.getText());
                bonTamux[2] = Double.parseDouble(BTCField.getText());
                bonTamux[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 5).collect(Collectors.toList()), bonTamux);
            
        }
        
        if(jCNinez.isSelected()){
            double bonN[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 7)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para niñez", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonN[0] = Double.parseDouble(BCField.getText());
                bonN[1] = Double.parseDouble(BLField.getText());
                bonN[2] = Double.parseDouble(BTCField.getText());
                bonN[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 8).collect(Collectors.toList()), bonN);
            
        }
        
        if(jCTamatan.isSelected()){
            double bonTama[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 7)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Tamatan", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonTama[0] = Double.parseDouble(BCField.getText());
                bonTama[1] = Double.parseDouble(BLField.getText());
                bonTama[2] = Double.parseDouble(BTCField.getText());
                bonTama[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 2).collect(Collectors.toList()), bonTama);
            
        }
        
        if(jCYumka.isSelected()){
            double bonY[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 7)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Yumka", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonY[0] = Double.parseDouble(BCField.getText());
                bonY[1] = Double.parseDouble(BLField.getText());
                bonY[2] = Double.parseDouble(BTCField.getText());
                bonY[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 10).collect(Collectors.toList()), bonY);
            
        }
        
        if(jCTlaco.isSelected()){
            double bonTla[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 7)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Tlaco", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonTla[0] = Double.parseDouble(BCField.getText());
                bonTla[1] = Double.parseDouble(BLField.getText());
                bonTla[2] = Double.parseDouble(BTCField.getText());
                bonTla[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 6).collect(Collectors.toList()), bonTla);
            
        }
        
        if(jCValle.isSelected()){
            double bonV[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 7)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Valle", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonV[0] = Double.parseDouble(BCField.getText());
                bonV[1] = Double.parseDouble(BLField.getText());
                bonV[2] = Double.parseDouble(BTCField.getText());
                bonV[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 9).collect(Collectors.toList()), bonV);
            
        }
        
        if(jCDiosP.isSelected()){
            double bonD[] = new double[4];
            javax.swing.JTextField BCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BLField = new javax.swing.JTextField(5);
            javax.swing.JTextField BTCField = new javax.swing.JTextField(5);
            javax.swing.JTextField BFSField = new javax.swing.JTextField(5);

            // Crear el panel y añadir los campos con etiquetas
            javax.swing.JPanel myPanel = new javax.swing.JPanel();
            myPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 7)); // 2 columnas, 5px de espacio
            myPanel.add(new javax.swing.JLabel("Bono del Coordinador:"));
            myPanel.add(BCField);
            myPanel.add(new javax.swing.JLabel("Bono del Líder:"));
            myPanel.add(BLField);
            myPanel.add(new javax.swing.JLabel("Bono de los Tiempos completos:"));
            myPanel.add(BTCField);
            myPanel.add(new javax.swing.JLabel("Bono de los Fines de semana:"));
            myPanel.add(BFSField);

            // Mostrar el panel dentro de un JOptionPane
            int result = JOptionPane.showConfirmDialog(null, myPanel, 
                     "Ingresar Bonos para Dios Padre", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                bonD[0] = Double.parseDouble(BCField.getText());
                bonD[1] = Double.parseDouble(BLField.getText());
                bonD[2] = Double.parseDouble(BTCField.getText());
                bonD[3] = Double.parseDouble(BFSField.getText());
            }
            
            cctrl.agregarBonos(pagos.stream().filter(emp -> emp.getEmpleado().getDestino().getId() == 7).collect(Collectors.toList()), bonD);
            
        }
        JOptionPane pane = new JOptionPane("Generando Tablas, por favor espere...", JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, null, new Object[]{}, null);
        final JDialog dialog = pane.createDialog("Cargando");
        dialog.setModal(false); // Permitir que el hilo principal continúe trabajando mientras se muestra el mensaje

        // Iniciar un hilo para mostrar el diálogo
        Thread loadingThread = new Thread(() -> dialog.setVisible(true));
        loadingThread.start();

        // Iniciar otro hilo para la inicialización de la vista
        new Thread(() -> {
            try {
        VistasController vctrl = new VistasController();
        List<PagoDestino> pagosDestinos = cctrl.pagosTotales(pagos);
        PagoTotal pagoTotal = cctrl.pagoTotalSuma(pagosDestinos);
        vctrl.vistaPagos(pagos, pagosDestinos, pagoTotal);
        SwingUtilities.invokeLater(dialog::dispose);
                
                // Dispose de la ventana actual si es necesario
                // dispose(); // Descomentar si necesitas cerrar la ventana actual
            } catch (Exception e) {
                e.printStackTrace(); // Manejo de excepciones
            }
        }).start();
        dispose();
    }//GEN-LAST:event_jBAceptar1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar1;
    private javax.swing.JCheckBox jCDiosP;
    private javax.swing.JCheckBox jCNinez;
    private javax.swing.JCheckBox jCTamatan;
    private javax.swing.JCheckBox jCTamux;
    private javax.swing.JCheckBox jCTlaco;
    private javax.swing.JCheckBox jCTuzoo;
    private javax.swing.JCheckBox jCValle;
    private javax.swing.JCheckBox jCYumka;
    private javax.swing.JCheckBox jCZoomat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
