/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.ExportarController;
import controller.PagoJpaController;
import controller.PagoTotalJpaController;
import controller.VistasController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Pago;
import model.PagoTotal;
import org.hibernate.Hibernate;

/**
 *
 * @author Soporte
 */
public class ExportarHistorial extends javax.swing.JFrame {

    /**
     * Creates new form ExportarHistorial
     */
    private final PagoTotalJpaController pTctrl = new PagoTotalJpaController();

    /**
     * Creates new form ExportarHistorial
     */
    public ExportarHistorial() {
        initComponents();
        // Cargar las fechas únicas en el JComboBox
        cargarFechas();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {            
            @Override
            public void windowClosing(WindowEvent e) {
                // Cierra esta ventana
                dispose();

                // Muestra la vista de CalendarioView
                VistasController vctrl = new VistasController();
                vctrl.iniciar();
                
            }
        });

    }

    private void cargarFechas() {
        jCFech.setModel(pTctrl.fechaComboBoxModel());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCFech = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECCIONA LA FECHA DE LA NOMINA A EXPORTAR");

        jCFech.setModel(pTctrl.fechaComboBoxModel());
        jCFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFechActionPerformed(evt);
            }
        });

        jButton1.setText("EXPORTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jCFech, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int selectedIndex = jCFech.getSelectedIndex();
       List<PagoTotal> pagosTotales = pTctrl.findPagoTotalEntities();
       //System.out.println(pagosTotales.get(selectedIndex));        
       ExportarController expctrl = new ExportarController(pagosTotales.get(selectedIndex));
       expctrl.exportarAExcel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCFechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFechActionPerformed
    }//GEN-LAST:event_jCFechActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCFech;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
