/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.ChecadorJpaController;
import controller.ClasificacionJpaController;
import controller.DestinoJpaController;
import controller.EmpleadoJpaController;
import controller.VistasController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Clasificacion;
import model.Destino;
import model.Empleado;

/**
 *
 * @author Soporte
 */
public class Inicio extends javax.swing.JFrame {
VistasController view = new VistasController();
    /**
     * Creates new form Inicio
     */
     List<Empleado> empleados;
    public Inicio(List<Empleado> empleados) {
        initComponents();
        this.empleados=empleados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("AÑADIR EMPLEADOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("EDITAR EMPLEADOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CALCULAR PAGOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("EXPORTAR PAGOS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("AÑADIR DESTINOS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChecadorJpaController cctrl = new ChecadorJpaController();
        EmpleadoJpaController ectrl = new EmpleadoJpaController();
        DestinoJpaController dctrl = new DestinoJpaController();   
        ClasificacionJpaController csctrl = new ClasificacionJpaController();
        List<Object[]> checador = cctrl.encontrarEmpleados();
        //System.out.printf("%-5s %-20s %-20s %-20s %-20s%n", "ID", "Name", "Last Name", "Branch", "Sorter2", "horario");
        for (Object[] row : checador) {
            // Asumimos que el orden es ID, Name, LastName, BranchName, Sorter2Name
            Integer id = (Integer) row[0];
            String name = (String) row[1];
            String lastName = (String) row[2];
            int iDBranch = (Integer) row[3];
            int hor = (Integer) row[4];
            int pues = (Integer) row[5];
            // Verificar si el empleado ya existe
            Empleado existingEmpleado = ectrl.findEmpleado(id);
            if (existingEmpleado != null) {
               // System.out.printf("Empleado con ID %d ya existe. Saltando al siguiente.%n", id);
                continue; // Saltar al siguiente empleado
            }

            // Crear el nuevo empleado
            Destino destino = dctrl.findDestino(iDBranch);
            Clasificacion horario = csctrl.findClasificacion(hor);
            Clasificacion puesto = csctrl.findClasificacion(pues);
            Empleado empleado = new Empleado(id, destino, horario, puesto, name+" "+lastName, 0, 0, true);            
            try {
                ectrl.create(empleado);
                //System.out.println(empleado.toString());
                //System.out.println("Empleado creado exitosamente.\n");
            } catch (Exception e) {
                System.err.println("Error al crear el empleado: " + e.getMessage());
            }            
            //System.out.printf("%-5d %-20s %-20s %-20s %-20s%n", id, name, lastName, branchName, sorter2Name);
        }
        JOptionPane OptionPane = new JOptionPane();
            OptionPane.showMessageDialog(null, 
                              "Empleados agregados exitosamente", 
                              "", 
                              JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        view.vistaEmpleados(this.empleados);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        view.vistaCalendario(this.empleados);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        view.vistaExportar();;
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ChecadorJpaController cctrl = new ChecadorJpaController();
        DestinoJpaController dctrl = new DestinoJpaController();  
        ClasificacionJpaController clcrl = new ClasificacionJpaController();
        List<Object[]> destinos = cctrl.encontrarDestinos();
        for(Object[] row : destinos){
            Integer id = (Integer) row[0];
            String nombre = (String) row[1];
            Destino findDestino = dctrl.findDestino(id);
            if(findDestino != null){
                continue;
            }else{
                Destino destino = new Destino(id, nombre, true);
                try {
                    dctrl.create(destino);
                } catch (Exception ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        List<Object[]> clasificaciones = cctrl.encontrarClasificaciones();
        JOptionPane OptionPane = new JOptionPane();
        for(Object[] row : clasificaciones){
            int id = (Integer) row[0];
            String nombre = (String) row[1];
            Clasificacion findClasificacion = clcrl.findClasificacion(id);
            if(findClasificacion != null){
                continue;
            }else{
                Clasificacion clasificacion = new Clasificacion(id, nombre);
                try {
                    clcrl.create(clasificacion);
                } catch (Exception ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
            OptionPane.showMessageDialog(null, 
                              "Destinos agregados exitosamente", 
                              "", 
                              JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
